# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20171005_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='DeviceModel',
        ),
    ]
