# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
        ('device', '0003_auto_20171005_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DeviceModel')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.SensorModel')),
            ],
            options={
                'db_table': 'time_line',
            },
        ),
    ]
